### PR TITLE
P0 - Alert & Button component

### PR DESCRIPTION
**Pull request by HarshithaKonduru214**
Please review the below 2 components. I have attached the output screenshots below.
image
image

### CODE REVIEW

**Review by ayush65 — APPROVED** [review]
Looks perfect 👍

**Comment by Rohitprasad83** [comment]
Looks great!

**Review by anupkgurung — COMMENTED** [review]
suggestion - colors could be more subtle

**Comment by saicharan-gouru** [comment]
Looks perfect.

**Comment by rohanmathur91** [comment]
Nicely done.

**Review by rohanmathur91 — APPROVED** [review]

**Review by NtshVrm — APPROVED** [review]

**Pull request merged**
